server:
  port: 8888

spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/reactive
    username: reactive
    password: reactive
    properties:
      lock_timeout: 40000
      statement_timeout: 40000
      idle_in_transaction_session_timeout: 40000
      connectTimeout: PT55S
#    pool:
#      enabled: true

